[[redirects]]
  from = "/anime/*"
  to = "https://anidrtst.onrender.com/anime/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/video/*"
  to = "https://anidrtst.onrender.com/video/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth/*"
  to = "https://anidrtst.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
