[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/anime*"
  to = "https://anidrtst.onrender.com/anime:splat"
  status = 200

[[redirects]]
  from = "/auth*"
  to = "https://anidrtst.onrender.com/auth:splat"
  status = 200

[[redirects]]
  from = "/video*"
  to = "https://anidrtst.onrender.com/video:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
